export const randomMovieDescription = [
  "A sci-fi thriller set in a post-apocalyptic world where robots have taken over.",
  "A romantic comedy about two strangers who meet on a deserted island.",
  "A historical drama based on the life of a famous artist.",
  "An action-packed adventure featuring a group of treasure hunters.",
  "A fantasy epic set in a magical kingdom threatened by darkness.",
  "A horror movie about a haunted house with a dark secret.",
  "A coming-of-age story set in a small town during the summer.",
  "A psychological thriller about a woman who suspects her neighbor is a serial killer.",
  "A comedy about a dysfunctional family reunited for a wedding.",
  "A mystery film following a detective solving a series of murders.",
  "A biographical film about a famous musician's rise to stardom.",
  "A science fiction movie exploring the consequences of time travel.",
  "A romantic drama set against the backdrop of war.",
  "An animated adventure featuring talking animals on a quest.",
  "A crime thriller centered around a heist gone wrong.",
  "A fantasy film about a young hero destined to save the world.",
  "A historical romance set in ancient Rome.",
  "A comedy about a group of friends on a road trip.",
  "A horror anthology featuring different supernatural stories.",
  "A psychological thriller about a woman with amnesia trying to uncover her past.",
  "A sci-fi action movie set in space during a galactic war.",
  "A romantic comedy about a fake relationship that turns real.",
  "A drama about the struggles of a family dealing with addiction.",
  "An adventure film about a quest for a mythical treasure.",
  "A mystery thriller with a plot twist at every turn.",
  "A biopic about a famous inventor and their groundbreaking discoveries.",
  "A supernatural horror film set in a haunted asylum.",
  "A coming-of-age comedy about teenagers navigating high school.",
  "A sci-fi dystopian film exploring a society divided by class.",
  "A romantic fantasy about star-crossed lovers from different worlds.",
  "A crime drama inspired by true events.",
  "A comedy about a group of retirees starting a new business venture.",
  "A horror movie set in a remote cabin in the woods.",
  "A historical epic about a legendary warrior's quest for vengeance.",
  "A romantic drama set in the roaring twenties.",
  "A fantasy adventure featuring mythical creatures and magical artifacts.",
  "A mystery thriller about a detective investigating a series of disappearances.",
  "A biographical film about a famous athlete's journey to the Olympics.",
  "A sci-fi action movie about a rebellion against a tyrannical government.",
  "A romantic comedy set in a small town during the holidays.",
  "A psychological horror film exploring the depths of the human mind.",
  "An animated musical about a group of animals putting on a talent show.",
  "A crime thriller about a cat-and-mouse game between a detective and a serial killer.",
  "A fantasy epic based on a popular book series.",
  "A romantic drama about a forbidden love affair.",
  "A comedy about a group of misfits competing in a quirky competition.",
  "A horror movie about a cursed artifact unleashing terror on its owners."
]

export const randomTvShowDescription = [
  "A high school teacher enters the criminal underworld to secure his family's future.",
  "Various families vie for power in a fantastical, medieval setting.",
  "A group of friends encounter mysterious forces while searching for a missing person.",
  "The daily lives of office employees are captured in a comedic documentary style.",
  "A group of friends navigate life and relationships in a major city.",
  "The reign and personal life of a historical figure is chronicled over decades.",
  "A lone warrior in a distant galaxy goes on various adventures.",
  "A modern-day detective solves crimes with the help of a close friend.",
  "An animated family deals with humorous and satirical situations in their town.",
  "A futuristic theme park offers guests an escape into a world where they can act without consequences.",
  "A monster hunter navigates a turbulent world while protecting a child connected to his destiny.",
  "An anthology series exploring dark and thought-provoking themes about society and technology.",
  "In a dystopian society, women are forced into roles as reproductive slaves.",
  "A small-time lawyer transforms into a morally ambiguous character in the legal world.",
  "A ruthless political figure manipulates his way to the top of the government.",
  "A group of survivors navigate a post-apocalyptic world filled with dangers.",
  "A woman discovers she has superpowers and must confront a powerful adversary.",
  "A forensic expert leads a double life as a vigilante serial killer.",
  "The intertwined lives of several families are explored across different time periods.",
  "A time-traveling hero explores the universe and solves problems with companions.",
  "A young hacker joins a group aiming to take down a powerful corporation.",
  "A teacher and a former student team up for illegal activities to improve their lives.",
  "An advertising executive in a past era deals with professional and personal challenges.",
  "A series exploring the human condition through various futuristic scenarios.",
  "Survivors navigate life in a world overrun by zombies.",
  "A small-town detective investigates a murder that shakes the community.",
  "A police officer leads a group of survivors in a dangerous, post-apocalyptic world.",
  "A time-traveling character solves problems and rights wrongs across the universe.",
  "A young hacker battles personal and societal issues while targeting a major corporation.",
  "An ambitious politician manipulates his way through the government.",
  "A crime-fighting duo solves mysteries in a modern setting.",
  "An animated series featuring a family's humorous exploits in their hometown.",
  "A group of people navigate their lives in a world where technology plays a significant role.",
  "A show that explores dark, dystopian themes through standalone episodes.",
  "A family deals with various life challenges in a satirical and comedic manner.",
  "A hero with special abilities fights against powerful enemies.",
  "A team of survivors faces numerous threats in a dangerous world.",
  "A professional with a hidden dark side leads a double life.",
  "A futuristic series that explores different facets of human nature.",
  "A series that delves into the intricacies of relationships and personal struggles.",
  "An investigator unravels complex mysteries with the help of a trusted partner.",
  "A young individual with special talents takes on a significant role in society.",
  "A story set in a fantastical world where different factions struggle for dominance.",
  "A comedy series depicting the humorous side of everyday life.",
  "An adventure series set in a distant, exotic location.",
  "A narrative that intertwines the lives of different characters in unexpected ways.",
  "A dramatic portrayal of historical events and figures.",
  "A series focused on the dark side of human nature and society.",
  "A team works together to overcome challenges in a dystopian world."
]

export const randomAnimeDescription = [
  "A young ninja dreams of becoming the leader of his village and must prove himself through various trials.",
  "Teenagers pilot giant robots to defend humanity from mysterious invaders.",
  "A schoolgirl discovers she can travel back in time and tries to fix past mistakes.",
  "A group of high school students form a club to explore supernatural occurrences in their town.",
  "An alien prince comes to Earth and learns the ways of humans while hiding from enemies.",
  "A warrior princess from a mystical land must find ancient artifacts to save her kingdom.",
  "A boy discovers he is the last of an ancient race and must protect a sacred tree.",
  "A group of friends gets transported to a video game world where they must fight to survive.",
  "A chef travels across the country to compete in cooking battles using magical ingredients.",
  "A detective with psychic abilities solves crimes while battling inner demons.",
  "A wandering samurai protects a small town from bandits while seeking redemption for his past.",
  "A girl finds a mysterious notebook that grants her the power to control people’s actions.",
  "A group of students are trapped in a haunted school and must uncover its secrets to escape.",
  "A musician with a magical instrument fights evil spirits threatening the world.",
  "A young boy befriends a dragon and together they embark on a quest to restore balance.",
  "A warrior from the future travels back in time to prevent a catastrophic event.",
  "A shy girl discovers she has a powerful alter-ego who awakens to protect her friends.",
  "A young alchemist searches for a mythical stone to restore his brother’s lost body.",
  "A guild of mages takes on dangerous missions while dealing with internal conflicts.",
  "A student council president leads a double life as a masked vigilante.",
  "A teenager discovers they are the reincarnation of an ancient hero destined to save the world.",
  "A group of kids find magical creatures and must protect them from an evil organization.",
  "A boy wakes up with no memory in a world where he has extraordinary combat skills.",
  "A high schooler gains the ability to see spirits and must help them find peace.",
  "A young girl joins a secretive organization that protects the world from mythical beasts.",
  "A teenager discovers a parallel world where they must fight to protect both realities.",
  "A group of pilots must defend Earth from alien invaders using advanced technology.",
  "A boy with a cursed eye seeks revenge against those who wronged him and his family.",
  "A young girl inherits a mysterious book that grants her magical powers.",
  "A team of bounty hunters travel across the galaxy taking on dangerous missions.",
  "A high schooler is transported to a fantasy world where they are mistaken for a legendary hero.",
  "A girl joins a prestigious academy where students learn to harness elemental powers.",
  "A boy discovers he can transform into a powerful creature and must keep his identity secret.",
  "A young hero must gather allies to fight against a powerful sorcerer threatening their world.",
  "A girl wakes up in a world where she must compete in deadly games to survive.",
  "A young warrior must find the scattered pieces of a magical sword to defeat an evil tyrant.",
  "A group of rebels fight against an oppressive government in a dystopian future.",
  "A student gains the ability to manipulate time and must use it to prevent disasters.",
  "A boy discovers he can summon powerful spirits to aid him in battle.",
  "A girl with amnesia must piece together her past while battling supernatural foes.",
  "A young hero must navigate a school for gifted individuals while uncovering hidden conspiracies.",
  "A group of friends discovers they have superpowers and must protect their city from villains.",
  "A warrior monk travels the land seeking to restore balance between good and evil.",
  "A young girl discovers she is the chosen one to wield a legendary weapon against dark forces.",
  "A group of teens must survive in a post-apocalyptic world filled with monstrous creatures.",
  "A young mage apprentices under a legendary sorcerer to unlock their true potential.",
  "A boy and his robotic companion embark on a journey to uncover ancient secrets.",
  "A high school student becomes a detective to solve the mystery of their missing family.",
  "A team of heroes with unique abilities must stop an interdimensional threat.",
  "A young warrior must unite various clans to prevent a looming war.",
  "A young hero embarks on a quest to become the strongest warrior in the land.",
    "A group of friends with special abilities protect their world from dark forces.",
    "A student discovers they have magical powers and must navigate a new world.",
    "A group of adventurers journey together to defeat an ancient evil.",
    "A young hero must train hard to achieve their dream of becoming a legendary figure.",
    "A futuristic city is protected by a team of super-powered individuals.",
    "A school for gifted youngsters trains them to harness their unique abilities.",
    "A warrior must confront their dark past while protecting those they love.",
    "A team of heroes band together to fight against an alien invasion.",
    "A mysterious transfer student brings change to a quiet high school.",
    "A hero must collect powerful artifacts to save their world from destruction.",
    "A young warrior faces numerous trials to prove their worth.",
    "A group of friends forms a team to compete in high-stakes tournaments.",
    "A young hero awakens to a hidden power and must protect their world.",
    "A student council with extraordinary abilities governs their school.",
    "A group of adventurers explores a vast, magical world filled with danger.",
    "A legendary hero returns to save their world from a new threat.",
    "A young hero trains under a wise master to fulfill their destiny.",
    "A young detective solves complex cases with the help of their friends.",
    "A group of rebels fights against an oppressive regime in a dystopian future.",
    "A high school student gains extraordinary powers and must keep them secret.",
    "A team of warriors defends their city from monstrous threats.",
    "A young hero must gather allies to fight against an evil empire.",
    "A magical girl discovers her true potential while battling dark forces.",
    "A hero must overcome their inner demons to save their world.",
    "A young prodigy navigates the challenges of a prestigious academy.",
    "A team of misfit heroes embarks on a journey to save their kingdom.",
    "A young warrior must master their powers to defeat a great evil.",
    "A mysterious organization fights to protect humanity from supernatural threats.",
    "A hero must balance their school life with their secret identity.",
    "A group of friends forms a club to solve supernatural mysteries.",
    "A young hero is chosen to wield a powerful weapon against dark forces.",
    "A group of warriors must defend their homeland from invaders.",
    "A young hero must uncover the secrets of their past to save the future.",
    "A team of heroes is assembled to combat a rising threat.",
    "A young warrior must navigate political intrigue and magical battles.",
    "A hero must unite various factions to prevent a catastrophic war.",
    "A young protagonist embarks on a journey to find their missing family.",
    "A group of friends must protect their town from supernatural occurrences.",
    "A hero must solve ancient puzzles to unlock their true power.",
    "A team of heroes trains together to face an impending disaster.",
    "A young protagonist is thrust into a war between good and evil.",
    "A hero must journey through dangerous lands to find a legendary artifact.",
    "A group of students with extraordinary abilities must save their school.",
    "A young hero is destined to bring peace to a war-torn world.",
    "A team of magical warriors protects their realm from dark sorcery.",
    "A hero must navigate a labyrinthine world filled with challenges.",
    "A group of young warriors trains to protect their city from evil.",
    "A young hero discovers a hidden world and must protect it from harm."
]

  export function formatTime(minutes) {
    const hours = Math.floor(minutes / 60);
    const remainingMinutes = minutes % 60;
    const hourString = hours > 0 ? `${hours} hr${hours > 1 ? 's' : ''}` : '';
    const minuteString = remainingMinutes > 0 ? `${remainingMinutes} min${remainingMinutes > 1 ? 's' : ''}` : '';
    
    if (hours > 0 && remainingMinutes > 0) {
      return `${hourString} ${minuteString}`;
    } else if (hours > 0) {
      return hourString;
    } else {
      return minuteString;
    }
  }

  export function generateUniqueId() {
    return Math.random().toString(36).substring(2) + Date.now().toString(36);
  }